routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('landing');
    Route::get('/tentang', 'HomeController@about')->name('about');
});

Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/detil-kelas', 'CoursesController@show')->name('show');
    Route::get('/pay', 'CoursesController@pay')->name('pay');
    Route::get('/start', 'CoursesController@start')->name('start');
});

Route::group(['prefix' => 'pengajar', 'as' => 'teachers.'], function () {
    Route::get('/', 'TeachersController@index')->name('index');
    Route::get('profil', 'TeachersController@show')->name('show');
});

// Admin Routes
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::group(['middleware' => 'guest:admin'], function () {
        Route::get('/login', 'DashboardController@showLoginForm')->name('login.form');
        Route::post('/login', 'DashboardController@login')->name('login');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');

        Route::group(['prefix' => 'kategori', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoriesController@index')->name('index');
            Route::get('/create', 'CategoriesController@create')->name('create');
            Route::post('/', 'CategoriesController@store')->name('store');
            Route::get('/{category}', 'CategoriesController@show')->name('show');
            Route::get('/{category}/edit', 'CategoriesController@edit')->name('edit');
            Route::put('/{category}', 'CategoriesController@update')->name('update');
            Route::delete('/{category}', 'CategoriesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'tanya-jawab', 'as' => 'faqs.'], function () {
            Route::get('/', 'FaqsController@index')->name('index');
            Route::get('/create', 'FaqsController@create')->name('create');
            Route::post('/', 'FaqsController@store')->name('store');
            Route::get('/{faq}', 'FaqsController@show')->name('show');
            Route::get('/{faq}/edit', 'FaqsController@edit')->name('edit');
            Route::put('/{faq}', 'FaqsController@update')->name('update');
            Route::delete('/{faq}', 'FaqsController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
            Route::get('/', 'CoursesController@index')->name('index');
            Route::delete('/{course}', 'CoursesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@index')->name('index');
            Route::get('/{user}', 'UsersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengajar', 'as' => 'lecturers.'], function () {
            Route::get('/', 'LecturersController@index')->name('index');
            Route::get('/belum-terverifikasi', 'LecturersController@unverified')->name('unverified');
            Route::patch('/{user}/verif', 'LecturersController@verif')->name('verif');
            Route::patch('/{user}/unverif', 'LecturersController@unverif')->name('unverif');
            Route::delete('/{user}', 'LecturersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'transaksi', 'as' => 'payments.'], function () {
            Route::get('/', 'PaymentsController@index')->name('index');
            Route::get('/belum-terverifikasi', 'PaymentsController@unverified')->name('unverified');
            Route::get('/menunggu-pembayaran', 'PaymentsController@pending')->name('pending');
            Route::patch('/{payment}/verif', 'PaymentsController@verif')->name('verif');
            Route::patch('/{payment}/unverif', 'PaymentsController@unverif')->name('unverif');
            Route::delete('/{payment}', 'PaymentsController@destroy')->name('destroy');
        });

    });
});

resources/views/admin/layouts/partials/breadcrumb.blade.php
<ol class="breadcrumb">

    <li class="breadcrumb-item">Home</li>

    @yield('breadcrumb')

    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
        <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="#">
                <i class="icon-speech"></i>
            </a>
            <a class="btn" href="./">
                <i class="icon-graph"></i>  Dashboard</a>
            <a class="btn" href="#">
                <i class="icon-settings"></i>  Settings</a>
        </div>
    </li>
</ol>

resources/views/admin/layouts/partials/errors_alert.blade.php
@if(! is_null(session('errors')))
    @if(count(array_filter(array_keys(session('errors')->getBag('default')->toArray()))) < 1)
    <div class="alert alert-danger">
        {{ session('errors')->first() }}
    </div>
    @endif
@endif

resources/views/admin/layouts/partials/navbar.blade.php
<a class="navbar-brand" href="#">
    <img src="{{ asset('brand.svg') }}" class="brand" alt="">
</a>
<div class="collapse navbar-collapse" id="navbarNav">
    <header class="navbar navbar-light">
        <button class="navbar-toggler sidebar-toggler" type="button" data-toggle="sidebar-show">
            <span class="navbar-toggler-icon"></span>
        </button>
    </header>
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="#">Dasbor<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Topik</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
    </ul>
</div>

resources/views/admin/layouts/partials/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-title">Utama</li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.dashboard.index') }}">
                    <i class="icon ion-md-trending-up"></i> Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.payments.index') }}">
                    <i class="icon ion-md-swap"></i> Transaksi
                    <span class="badge badge-primary">NEW</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.users.index') }}">
                    <i class="icon ion-md-person"></i> Pengguna
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.lecturers.index') }}">
                    <i class="icon ion-md-school"></i> Pengajar
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.courses.index') }}">
                    <i class="icon ion-md-laptop"></i> Kelas
                </a>
            </li>
            <li class="nav-title">Pengaturan Web</li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.categories.index') }}">
                    <i class="icon ion-md-filing"></i> Kategori
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.faqs.index') }}">
                    <i class="icon ion-md-chatboxes"></i> Tanya Jawab
                </a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="icon ion-md-information-circle"></i> Tentang
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <i class="icon ion-md-contacts"></i> Kontak
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>