routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('landing');
    Route::get('/tentang', 'HomeController@about')->name('about');
});

Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/detil-kelas', 'CoursesController@show')->name('show');
    Route::get('/pay', 'CoursesController@pay')->name('pay');
    Route::get('/start', 'CoursesController@start')->name('start');
});

Route::group(['prefix' => 'pengajar', 'as' => 'teachers.'], function () {
    Route::get('/', 'TeachersController@index')->name('index');
    Route::get('profil', 'TeachersController@show')->name('show');
});

// Admin Routes
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::group(['middleware' => 'guest:admin'], function () {
        Route::get('/login', 'DashboardController@showLoginForm')->name('login.form');
        Route::post('/login', 'DashboardController@login')->name('login');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');

        Route::group(['prefix' => 'kategori', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoriesController@index')->name('index');
            Route::get('/create', 'CategoriesController@create')->name('create');
            Route::post('/', 'CategoriesController@store')->name('store');
            Route::get('/{category}', 'CategoriesController@show')->name('show');
            Route::get('/{category}/edit', 'CategoriesController@edit')->name('edit');
            Route::put('/{category}', 'CategoriesController@update')->name('update');
            Route::delete('/{category}', 'CategoriesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'tanya-jawab', 'as' => 'faqs.'], function () {
            Route::get('/', 'FaqsController@index')->name('index');
            Route::get('/create', 'FaqsController@create')->name('create');
            Route::post('/', 'FaqsController@store')->name('store');
            Route::get('/{faq}', 'FaqsController@show')->name('show');
            Route::get('/{faq}/edit', 'FaqsController@edit')->name('edit');
            Route::put('/{faq}', 'FaqsController@update')->name('update');
            Route::delete('/{faq}', 'FaqsController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
            Route::get('/', 'CoursesController@index')->name('index');
            Route::delete('/{course}', 'CoursesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@index')->name('index');
            Route::get('/{user}', 'UsersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengajar', 'as' => 'lecturers.'], function () {
            Route::get('/', 'LecturersController@index')->name('index');
            Route::get('/belum-terverifikasi', 'LecturersController@unverified')->name('unverified');
            Route::patch('/{user}/verif', 'LecturersController@verif')->name('verif');
            Route::patch('/{user}/unverif', 'LecturersController@unverif')->name('unverif');
            Route::delete('/{user}', 'LecturersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'transaksi', 'as' => 'payments.'], function () {
            Route::get('/', 'PaymentsController@index')->name('index');
            Route::get('/belum-terverifikasi', 'PaymentsController@unverified')->name('unverified');
            Route::get('/menunggu-pembayaran', 'PaymentsController@pending')->name('pending');
            Route::patch('/{payment}/verif', 'PaymentsController@verif')->name('verif');
            Route::patch('/{payment}/unverif', 'PaymentsController@unverif')->name('unverif');
            Route::delete('/{payment}', 'PaymentsController@destroy')->name('destroy');
        });

    });
});

app/Http/Controllers/Admin/PaymentsController.php
<?php
/**
 * @author<rendy> at 06/02/2019
 */

namespace App\Http\Controllers\Admin;


use App\DataTables\PaymentsDataTable;
use App\DataTables\UnverifiedPaymentsDataTable;
use App\DataTables\WaitingPaymentsDataTable;
use App\Entities\Payment;
use App\Http\Controllers\Controller;

class PaymentsController extends Controller
{

    public function index(PaymentsDataTable $dataTable)
    {
        return $dataTable->render('admin.payments.index');
    }

    public function unverified(UnverifiedPaymentsDataTable $dataTable)
    {
        return $dataTable->render('admin.payments.index_unverified');
    }

    public function pending(WaitingPaymentsDataTable $dataTable)
    {
        return $dataTable->render('admin.payments.index_pending');
    }

    public function verif(Payment $payment)
    {
        return $payment->upgradeStatus()
            ? redirect()->back()->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function unverif(Payment $payment)
    {
        return $payment->downgradeStatus()
            ? redirect()->back()->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function destroy(Payment $payment)
    {
        return $payment->delete()
            ? redirect()->back()->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

}

resources/views/admin/payments/action.blade.php
@if($status == 'Dibayar')
    <form action="{{ route('admin.payments.unverif', ['payment' => $id]) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('patch') }}
        <button class="btn btn-sm btn-primary" onclick="return confirm('Batalkan verifikasi pembayaran transaksi ?')">
            UNVERIF
        </button>
    </form>
@elseif ($status == 'Menunggu verifikasi')
    <form action="{{ route('admin.payments.verif', ['payment' => $id]) }}" method="post">
        {{ csrf_field() }}
        {{ method_field('patch') }}
        <button class="btn btn-sm btn-primary" onclick="return confirm('Verifikasi pembayaran transaksi ?')">
            VERIF
        </button>
    </form>
@endif

<form action="{{ route('admin.payments.destroy', ['payment' => $id]) }}" method="post">
    {!! csrf_field() !!}
    {!! method_field('delete') !!}

    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
        <i class="icons ion-md-trash"></i>
    </button>
</form>

resources/views/admin/payments/index.blade.php
@extends('admin.layouts.app')
@section('page_title', 'Transaksi')


@section('breadcrumb')
    <li class="breadcrumb-item active">List Transaksi Sukses</li>
@endsection

@section('body')
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>List Transaksi Sukses</h3>

                <ul class="nav nav-tabs pt-4" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" aria-selected="true" href="{{ route('admin.payments.index') }}">
                            Sukses
                            <i class="ion-md-checkmark"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.unverified') }}">
                            Menunggu Verifikasi
                            <i class="ion-md-warning"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.pending') }}">
                            Menunggu Pembayaran
                            <i class="ion-md-clock"></i>
                        </a>
                    </li>
                </ul>

                <div class="pt-3">
                    {!! $dataTable->table(['class' => 'table table-bordered']) !!}
                </div>

            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
@endsection

@push('foots') {!! $dataTable->scripts() !!} @endpush

resources/views/admin/payments/index_pending.blade.php
@extends('admin.layouts.app')
@section('page_title', 'Transaksi')


@section('breadcrumb')
    <li class="breadcrumb-item active">List Transaksi Pending</li>
@endsection

@section('body')
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>List Transaksi Pending</h3>

                <ul class="nav nav-tabs pt-4" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.index') }}">
                            Sukses
                            <i class="ion-md-checkmark"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.unverified') }}">
                            Menunggu Verifikasi
                            <i class="ion-md-warning"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-selected="true" href="{{ route('admin.payments.pending') }}">
                            Menunggu Pembayaran
                            <i class="ion-md-clock"></i>
                        </a>
                    </li>
                </ul>

                <div class="pt-3">
                    {!! $dataTable->table(['class' => 'table table-bordered']) !!}
                </div>

            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
@endsection

@push('foots') {!! $dataTable->scripts() !!} @endpush

resources/views/admin/payments/index_unverified.blade.php
@extends('admin.layouts.app')
@section('page_title', 'Transaksi')


@section('breadcrumb')
    <li class="breadcrumb-item active">List Transaksi Sukses</li>
@endsection

@section('body')
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>List Transaksi Sukses</h3>

                <ul class="nav nav-tabs pt-4" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.index') }}">
                            Sukses
                            <i class="ion-md-checkmark"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-selected="true" href="{{ route('admin.payments.unverified') }}">
                            Menunggu Verifikasi
                            <i class="ion-md-warning"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-selected="false" href="{{ route('admin.payments.pending') }}">
                            Menunggu Pembayaran
                            <i class="ion-md-clock"></i>
                        </a>
                    </li>
                </ul>

                <div class="pt-3">
                    {!! $dataTable->table(['class' => 'table table-bordered']) !!}
                </div>

            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
@endsection

@push('foots') {!! $dataTable->scripts() !!} @endpush