routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('landing');
    Route::get('/tentang', 'HomeController@about')->name('about');
});

Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/detil-kelas', 'CoursesController@show')->name('show');
    Route::get('/pay', 'CoursesController@pay')->name('pay');
    Route::get('/start', 'CoursesController@start')->name('start');
});

Route::group(['prefix' => 'pengajar', 'as' => 'teachers.'], function () {
    Route::get('/', 'TeachersController@index')->name('index');
    Route::get('profil', 'TeachersController@show')->name('show');
});

// Admin Routes
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::group(['middleware' => 'guest:admin'], function () {
        Route::get('/login', 'DashboardController@showLoginForm')->name('login.form');
        Route::post('/login', 'DashboardController@login')->name('login');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');

        Route::group(['prefix' => 'kategori', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoriesController@index')->name('index');
            Route::get('/create', 'CategoriesController@create')->name('create');
            Route::post('/', 'CategoriesController@store')->name('store');
            Route::get('/{category}', 'CategoriesController@show')->name('show');
            Route::get('/{category}/edit', 'CategoriesController@edit')->name('edit');
            Route::put('/{category}', 'CategoriesController@update')->name('update');
            Route::delete('/{category}', 'CategoriesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'tanya-jawab', 'as' => 'faqs.'], function () {
            Route::get('/', 'FaqsController@index')->name('index');
            Route::get('/create', 'FaqsController@create')->name('create');
            Route::post('/', 'FaqsController@store')->name('store');
            Route::get('/{faq}', 'FaqsController@show')->name('show');
            Route::get('/{faq}/edit', 'FaqsController@edit')->name('edit');
            Route::put('/{faq}', 'FaqsController@update')->name('update');
            Route::delete('/{faq}', 'FaqsController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
            Route::get('/', 'CoursesController@index')->name('index');
            Route::delete('/{course}', 'CoursesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@index')->name('index');
            Route::get('/{user}', 'UsersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengajar', 'as' => 'lecturers.'], function () {
            Route::get('/', 'LecturersController@index')->name('index');
            Route::get('/belum-terverifikasi', 'LecturersController@unverified')->name('unverified');
            Route::patch('/{user}/verif', 'LecturersController@verif')->name('verif');
            Route::patch('/{user}/unverif', 'LecturersController@unverif')->name('unverif');
            Route::delete('/{user}', 'LecturersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'transaksi', 'as' => 'payments.'], function () {
            Route::get('/', 'PaymentsController@index')->name('index');
            Route::get('/belum-terverifikasi', 'PaymentsController@unverified')->name('unverified');
            Route::get('/menunggu-pembayaran', 'PaymentsController@pending')->name('pending');
            Route::patch('/{payment}/verif', 'PaymentsController@verif')->name('verif');
            Route::patch('/{payment}/unverif', 'PaymentsController@unverif')->name('unverif');
            Route::delete('/{payment}', 'PaymentsController@destroy')->name('destroy');
        });

    });
});

app/Http/Controllers/Admin/FaqsController.php
<?php
/**
 * @author<rendy> at 03/02/2019
 */

namespace App\Http\Controllers\Admin;


use App\DataTables\FaqsDataTable;
use App\Entities\Faq;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FaqsController extends Controller
{
    public function index(FaqsDataTable $dataTable)
    {
        return $dataTable->render('admin.faqs.index');
    }

    public function create()
    {
        return view('admin.faqs.create');
    }

    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'question' => 'required',
            'answer' => 'required'
        ]);

        $faq = new Faq();
        $faq->fill($data);
        $faq->save();

        return $faq->save()
            ? redirect()->route('admin.faqs.index')->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function show(Faq $faq)
    {
        return view('admin.faqs.show', compact('faq'));
    }

    public function edit(Faq $faq)
    {
        return view('admin.faqs.edit', compact('faq'));
    }

    public function update(Request $request, Faq $faq)
    {
        $data = $this->validate($request, [
            'question' => 'required',
            'answer' => 'required'
        ]);

        $faq->fill($data);
        $faq->save();

        return $faq->save()
            ? redirect()->route('admin.faqs.index')->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function destroy(Faq $faq)
    {
        return $faq->delete()
            ? redirect()->back()->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }
}

resources/views/admin/faqs/action.blade.php
<form action="{{ route('admin.faqs.destroy', ['faq' => $id]) }}" method="post">
    {!! csrf_field() !!}
    {!! method_field('delete') !!}

    <a href="{{ route('admin.faqs.show', ['faq' => $id]) }}" class="btn btn-sm btn-primary">
        <i class="ion-md-eye"></i>
    </a>

    <a href="{{ route('admin.faqs.edit', ['faq' => $id]) }}" class="btn btn-sm btn-warning">
        <i class="ion-md-create"></i>
    </a>

    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
        <i class="icons ion-md-trash"></i>
    </button>
</form>

resources/views/admin/faqs/create.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Tanya Jawab Baru')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.faqs.index') }}">List Tanya Jawab</a>
    </li>
    <li class="breadcrumb-item active">Tanya Jawab Baru</li>
@endsection

@push('heads')
    <script src="{{ asset('js/ckeditor.js') }}"></script>
@endpush

@section('body')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h3>Tanya Jawab Baru</h3>

                    <form class="pt-2" action="{{ route('admin.faqs.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="">Pertanyaan</label>
                            <input type="text" name="question"  class="form-control {{ set_error('question') }}" value="{{ old('question') }}">
                            {!! get_error('question') !!}
                        </div>

                        <div class="form-group">
                            <label for="">Jawab</label>
                            <textarea name="answer" id="ckeditor" cols="30" rows="40" class="form-control">
                                {!! old('answer') !!}
                            </textarea>
                            {!! get_error('answer') !!}
                        </div>
                        <button class="btn btn-success">
                            <span class="icon ion-md-add"></span> Tambah
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('foots')
    <script>
        ClassicEditor
            .create(document.querySelector( '#ckeditor' ))
    </script>
@endpush

resources/views/admin/faqs/edit.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Edit Tanya Jawab')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.faqs.index') }}">List Tanya Jawab</a>
    </li>
    <li class="breadcrumb-item active">Edit Tanya Jawab {{ $faq->name }}</li>
@endsection

@push('heads')
    <script src="{{ asset('js/ckeditor.js') }}"></script>
@endpush

@section('body')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Edit Tanya Jawab {{ $faq->question }}</h3>

                    <form class="pt-2" action="{{ route('admin.categories.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="">Pertanyaan</label>
                            <input type="text" name="question"  class="form-control {{ set_error('name') }}" value="{{ $faq->question }}">
                            {!! get_error('question') !!}
                        </div>

                        <div class="form-group">
                            <label for="">Ikon</label>
                            <textarea name="answer" id="ckeditor" cols="30" rows="10">
                                {!! $faq->answer !!}
                            </textarea>
                            <input type="file" name="answer"  class="{{ set_error('answer') }}">
                            {!! get_error('answer') !!}
                        </div>
                        <button class="btn btn-warning">
                            <span class="icon ion-md-create"></span> Simpan
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('foots')
    <script>
        ClassicEditor
            .create(document.querySelector( '#ckeditor' ))
    </script>
@endpush

resources/views/admin/faqs/index.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Kategori')

@section('breadcrumb')
    <li class="breadcrumb-item active">List Tanya Jawab</li>
@endsection

@section('body')
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>List Tanya Jawab</h3>

                <a href="{{ route('admin.faqs.create') }}" class="btn btn-primary pull-right pt-2">
                    <i class="icon ion-md-add"></i> Baru
                </a>

                <div class="pt-3">
                    {!! $dataTable->table(['class' => 'table table-bordered']) !!}
                </div>

            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
@endsection

@push('foots') {!! $dataTable->scripts() !!} @endpush

resources/views/admin/faqs/show.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Detil Kategori')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.categories.index') }}">List Kategori</a>
    </li>
    <li class="breadcrumb-item active">Detil Kategori {{ $category->name }}</li>
@endsection

@section('body')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>{{ $category->name }}</h3>
                    @if (isset($category->icon))
                        <img src="{{ storage_asset($category->icon) }}" class="img-circle" width="80" alt="">
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection