routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('landing');
    Route::get('/tentang', 'HomeController@about')->name('about');
});

Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/detil-kelas', 'CoursesController@show')->name('show');
    Route::get('/pay', 'CoursesController@pay')->name('pay');
    Route::get('/start', 'CoursesController@start')->name('start');
});

Route::group(['prefix' => 'pengajar', 'as' => 'teachers.'], function () {
    Route::get('/', 'TeachersController@index')->name('index');
    Route::get('profil', 'TeachersController@show')->name('show');
});

// Admin Routes
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {

    Route::group(['middleware' => 'guest:admin'], function () {
        Route::get('/login', 'DashboardController@showLoginForm')->name('login.form');
        Route::post('/login', 'DashboardController@login')->name('login');
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');

        Route::group(['prefix' => 'kategori', 'as' => 'categories.'], function () {
            Route::get('/', 'CategoriesController@index')->name('index');
            Route::get('/create', 'CategoriesController@create')->name('create');
            Route::post('/', 'CategoriesController@store')->name('store');
            Route::get('/{category}', 'CategoriesController@show')->name('show');
            Route::get('/{category}/edit', 'CategoriesController@edit')->name('edit');
            Route::put('/{category}', 'CategoriesController@update')->name('update');
            Route::delete('/{category}', 'CategoriesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'tanya-jawab', 'as' => 'faqs.'], function () {
            Route::get('/', 'FaqsController@index')->name('index');
            Route::get('/create', 'FaqsController@create')->name('create');
            Route::post('/', 'FaqsController@store')->name('store');
            Route::get('/{faq}', 'FaqsController@show')->name('show');
            Route::get('/{faq}/edit', 'FaqsController@edit')->name('edit');
            Route::put('/{faq}', 'FaqsController@update')->name('update');
            Route::delete('/{faq}', 'FaqsController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'kelas', 'as' => 'courses.'], function () {
            Route::get('/', 'CoursesController@index')->name('index');
            Route::delete('/{course}', 'CoursesController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@index')->name('index');
            Route::get('/{user}', 'UsersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'pengajar', 'as' => 'lecturers.'], function () {
            Route::get('/', 'LecturersController@index')->name('index');
            Route::get('/belum-terverifikasi', 'LecturersController@unverified')->name('unverified');
            Route::patch('/{user}/verif', 'LecturersController@verif')->name('verif');
            Route::patch('/{user}/unverif', 'LecturersController@unverif')->name('unverif');
            Route::delete('/{user}', 'LecturersController@destroy')->name('destroy');
        });

        Route::group(['prefix' => 'transaksi', 'as' => 'payments.'], function () {
            Route::get('/', 'PaymentsController@index')->name('index');
            Route::get('/belum-terverifikasi', 'PaymentsController@unverified')->name('unverified');
            Route::get('/menunggu-pembayaran', 'PaymentsController@pending')->name('pending');
            Route::patch('/{payment}/verif', 'PaymentsController@verif')->name('verif');
            Route::patch('/{payment}/unverif', 'PaymentsController@unverif')->name('unverif');
            Route::delete('/{payment}', 'PaymentsController@destroy')->name('destroy');
        });

    });
});

app/Http/Controllers/Admin/CategoriesController.php
<?php
/**
 * @author<rendy> at 03/02/2019
 */

namespace App\Http\Controllers\Admin;


use App\DataTables\CategoriesDataTable;
use App\Entities\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    public function index(CategoriesDataTable $dataTable)
    {
        return $dataTable->render('admin.categories.index');
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'icon' => 'image'
        ]);

        $category = new Category();
        if ($request->hasFile('icon')) {
            $category->fill([
                'name' => $request->input('name'),
                'icon' => $request->file('icon')->store('icons')
            ]);
        } else {
            $category->fill($request->only('name'));
        }

        $category->save();

        return $category->save()
            ? redirect()->route('admin.categories.index')->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    public function update(Request $request, Category $category)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'icon' => 'photo'
        ]);
        if ($request->hasFile('icon')) {
            $category->fill([
                'name' => $request->input('name'),
                'icon' => $request->file('icon')->store('icons')
            ]);
        } else {
            $category->fill($request->only('name'));
        }
        $category->save();

        return $category->save()
            ? redirect()->route('admin.categories.index')->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

    public function destroy(Category $category)
    {
        return $category->delete()
            ? redirect()->back()->with('Success')
            : redirect()->back()->withErrors('Internal Server Error');
    }

}

resources/views/admin/categories/action.blade.php
<form action="{{ route('admin.categories.destroy', ['category' => $id]) }}" method="post">
    {!! csrf_field() !!}
    {!! method_field('delete') !!}

    <a href="{{ route('admin.categories.show', ['category' => $id]) }}" class="btn btn-sm btn-primary">
        <i class="ion-md-eye"></i>
    </a>

    <a href="{{ route('admin.categories.edit', ['category' => $id]) }}" class="btn btn-sm btn-warning">
        <i class="ion-md-create"></i>
    </a>

    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin menghapus data ?')">
        <i class="icons ion-md-trash"></i>
    </button>
</form>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Buat kategori baru')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.categories.index') }}">List Kategori</a>
    </li>
    <li class="breadcrumb-item active">Kategori baru</li>
@endsection

@section('body')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Kategori Baru</h3>

                    <form class="pt-2" action="{{ route('admin.categories.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="text" name="name"  class="form-control {{ set_error('name') }}" value="{{ old('name') }}">
                            {!! get_error('name') !!}
                        </div>
                        <div class="form-group">
                            <label for="">Ikon</label>
                            <input type="file" name="icon"  class="{{ set_error('icon') }}">
                            {!! get_error('icon') !!}
                        </div>
                        <button class="btn btn-success">
                            <span class="icon ion-md-add"></span> Tambah
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Edit Kategori')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.categories.index') }}">List Kategori</a>
    </li>
    <li class="breadcrumb-item active">Edit Kategori {{ $category->name }}</li>
@endsection

@section('body')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Edit Kategori {{ $category->name }}</h3>

                    <form class="pt-2" action="{{ route('admin.categories.update', ['category' => $category]) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="">Nama</label>
                            <input type="text" name="name"  class="form-control {{ set_error('name') }}" value="{{ $category->name }}">
                            {!! get_error('name') !!}
                        </div>
                        @if(isset($category->icon))
                        <div class="form-group">
                            <img src="{{ storage_asset($category->icon) }}" width="60" alt="">
                        </div>
                            <p>Pilih file untuk mengubah ikon</p>
                        @endif
                        <div class="form-group">
                            <label for="">Ikon</label>
                            <input type="file" name="icon"  class="{{ set_error('icon') }}">
                            {!! get_error('icon') !!}
                        </div>
                        <button class="btn btn-warning">
                            <span class="icon ion-md-create"></span> Simpan
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Kategori')

@section('breadcrumb')
    <li class="breadcrumb-item active">List Kategori</li>
@endsection

@section('body')
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>List Kategori</h3>

                <a href="{{ route('admin.categories.create') }}" class="btn btn-primary pull-right pt-2">
                    <i class="icon ion-md-add"></i> Baru
                </a>

                <div class="pt-3">
                    {!! $dataTable->table(['class' => 'table table-bordered']) !!}
                </div>

            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
@endsection

@push('foots') {!! $dataTable->scripts() !!} @endpush

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')

@section('page_title', 'Detil Kategori')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="{{ route('admin.categories.index') }}">List Kategori</a>
    </li>
    <li class="breadcrumb-item active">Detil Kategori {{ $category->name }}</li>
@endsection

@section('body')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>{{ $category->name }}</h3>
                    @if (isset($category->icon))
                        <img src="{{ storage_asset($category->icon) }}" class="img-circle" width="80" alt="">
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection